(define int-bits 32)
(define (xor a b)
  (and (or a b) (not (and a b))))
(define (bitOr a b)
  (if (or (= a 1) (= b 1))
      1
      0
      ))
(define (bitAnd a b)
  (if (and (= a 1) (= b 1))
      1
      0
  ))
(define (bitXor a b)
  (if (xor (= a 1) (= b 1))
      1
      0
  ))
(define (bitNot a)
  (if (= a 1)
      0
      1
      ))
(define (mkSize ls n)
  (define (mkSizei ls n a)
    (cond ((= n 0) a)
          ((null? ls) (mkSizei ls (- n 1) (append a '(0))))
          (else (mkSizei (cdr ls) (- n 1) (append a (list (car ls)))))
          ))
  (mkSizei ls n '())
  )
(define (half-adder bita bitb)
  (list (bitXor bita bitb) (bitAnd bita bitb)))
(define (full-adder bita bitb cin)
  (list (bitXor cin (bitXor bita bitb)) (bitOr (bitAnd bita bitb) (bitAnd (bitXor bita bitb) cin))))

(define (bit-add bitsa bitsb)
  (if (or (null? bitsa) (null? bitsb))
      (mkSize (append bitsa bitsb) int-bits)
      (let ((sum (half-adder (car bitsa) (car bitsb))))
        (mkSize (append (list (car sum)) (bit-add-helper (cdr bitsa) (cdr bitsb) (cadr sum))) int-bits))
     ))
(define (bit-add-helper bitsa bitsb cin)
  (cond
    ((and (null? bitsa) (null? bitsb))
     (if (= cin 1)
         '(1)
         '()
         ))
    ((null? bitsa) (bit-add-helper '(0) bitsb cin))
    ((null? bitsb) (bit-add-helper bitsa '(0) cin))
    (else (let ((sum (full-adder (car bitsa) (car bitsb) cin)))
            (append (list (car sum)) (bit-add-helper (cdr bitsa) (cdr bitsb) (cadr sum)))
            ))
    ))
(define (count ls)
  (define (count-i ls a)
    (if (null? ls)
        a
        (count-i (cdr ls) (+ a 1))
        ))
  (count-i ls 0))
(define (lsNot bits)
  (define (lsNoti bits res)
    (if (null? bits)
        res
        (lsNoti (cdr bits) (append res (list (bitNot (car bits)))))
        ))
  (lsNoti bits '())
  )
(define (bit-sub bitsa bitsb)
  (if (not (and (= (count bitsa) int-bits) (= (count bitsb) int-bits)))
      (bit-sub (mkSize bitsa int-bits) (mkSize bitsb int-bits))
      (mkSize (bit-add (bit-add bitsa (mkSize '(1) int-bits)) (lsNot bitsb)) int-bits)
      ))
(define (last ls)
  (item (count ls) ls))
(define (item n ls)
  (if (or (= n 1) (< n 1))
      (car ls)
      (item (- n 1) (cdr ls))
      ))
(define (bit-mult bitsa bitsb)
  (define (bit-mult-iter bitsa bitsb res)
    (cond ((null? bitsb) res)
          ((= (last bitsb) 1)
           (bit-mult-iter bitsa
                          (mkSize bitsb (- (count bitsb) 1)) (bit-add (l-shift res) bitsa)))
          (else (bit-mult-iter bitsa (mkSize bitsb (- (count bitsb) 1)) (l-shift res)))
      ))
  (bit-mult-iter bitsa bitsb (mkSize '(0) int-bits)))
(define (l-shift bits)
  (mkSize (append '(0) bits) int-bits))
(define (r-shift bits)
  (mkSize (cdr bits) int-bits))
(define (bit-expt bitsa bitsb)
  (define (bit-expt-iter bitsa bitsb res)
    (cond ((null? bitsb) res)
          ((= (last bitsb) 1)
           (bit-expt-iter bitsa (mkSize bitsb (- (count bitsb) 1)) (bit-mult (bit-mult res res) bitsa)))
          (else (bit-expt-iter bitsa (mkSize bitsb (- (count bitsb) 1)) (bit-mult res res)))
      ))
  (bit-expt-iter bitsa bitsb (mkSize '(1) int-bits))
  )
(define (last-one bits)
  (define (last-one-helper bits n)
    (cond ((null? bits) n)
          ((= (car bits) 1) (last-one-helper (cdr bits) (- int-bits (count bits))))
          (else (last-one-helper (cdr bits) n))
      ))
  (+ (last-one-helper bits -2) 1)
  )
(define (b>= ba bb)
  (let ((bitsa (mkSize ba int-bits)) (bitsb (mkSize bb int-bits)))
    (cond ((and (equal? bitsa bitsb) (equal? bitsa (mkSize '(0) int-bits))) #t)
        ((= (last bitsa) (last bitsb))
         (b>= (mkSize (append '(0) bitsa) int-bits) (mkSize (append '(0) bitsb) int-bits)))
        (else (= (last bitsa) 1))
    )))
(define (bit-div bitsa bitsb)
  (define (devide-helper bitsa bitsb n res)
    (if (or (> n 0) (= n 0))
        (let ((to-test (insert n 0 bitsb int-bits)))
          (if (b>= bitsa to-test)
              (devide-helper (bit-sub bitsa to-test) bitsb (- n 1) (insert 1 1 res int-bits))
              (devide-helper bitsa bitsb (- n 1) (insert 1 0 res int-bits))
             )) 
        res
        )
    )
  (devide-helper (mkSize bitsa int-bits) (mkSize bitsb int-bits)
                 (- int-bits (last-one (mkSize bitsb int-bits)))
                 (mkSize '(0) int-bits)))
(define (bit-mod bitsa bitsb)
  (define (mod-helper bitsa bitsb n)
    (if (or (> n 0) (= n 0))
        (let ((to-test (insert n 0 bitsb int-bits)))
          (if (b>= bitsa to-test)
              (mod-helper (bit-sub bitsa to-test) bitsb (- n 1))
              (mod-helper bitsa bitsb (- n 1))
              ))
        bitsa))
  (mod-helper (mkSize bitsa int-bits) (mkSize bitsb int-bits)
                 (- int-bits (last-one (mkSize bitsb int-bits)))))
(define (insert n as ls size)
  (define (iter n as ls)
    (if (= n 0)
      ls
      (insert (- n 1) as (cons as ls) size)
      ))
  (mkSize (iter n as ls) size))